[project]
name = "moist-meat"
version = "0.1.0"
dependencies = [
    "firebase-admin",
    "polars",
    "plotly",
    "kaleido",
    "ty",
    "python-dateutil",
    "numpy",
]

[tool.ty]
[tool.ty.rules]
unresolved-attribute = "ignore"
